// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZuGlPD_Tnj80Wc9XuTLhUyvvID-x7E80',
    appId: '1:1005916963401:web:99e6c1cb4b9adf6a577598',
    messagingSenderId: '1005916963401',
    projectId: 'conecta-mais-ee2b4',
    authDomain: 'conecta-mais-ee2b4.firebaseapp.com',
    storageBucket: 'conecta-mais-ee2b4.appspot.com',
    measurementId: 'G-00BEE1TN7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZC0Hv0fugK9mnKmA4sqV0eQWa8yM0Wm8',
    appId: '1:1005916963401:android:0c6830c9f695212f577598',
    messagingSenderId: '1005916963401',
    projectId: 'conecta-mais-ee2b4',
    storageBucket: 'conecta-mais-ee2b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoEZwCSBz0UBZ_d7wlTHgky6t7zlkan70',
    appId: '1:1005916963401:ios:1fe7566300325d3b577598',
    messagingSenderId: '1005916963401',
    projectId: 'conecta-mais-ee2b4',
    storageBucket: 'conecta-mais-ee2b4.appspot.com',
    androidClientId: '1005916963401-n2re3jaihjd9v27cbimur1r4eq2g3m0s.apps.googleusercontent.com',
    iosClientId: '1005916963401-80togpk2bglhd7b7abkei9kh66gqc8r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.admconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoEZwCSBz0UBZ_d7wlTHgky6t7zlkan70',
    appId: '1:1005916963401:ios:1fe7566300325d3b577598',
    messagingSenderId: '1005916963401',
    projectId: 'conecta-mais-ee2b4',
    storageBucket: 'conecta-mais-ee2b4.appspot.com',
    androidClientId: '1005916963401-n2re3jaihjd9v27cbimur1r4eq2g3m0s.apps.googleusercontent.com',
    iosClientId: '1005916963401-80togpk2bglhd7b7abkei9kh66gqc8r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.admconnect',
  );
}
